### ISSUE TITLE
Peer to peer code review (Module 2 week 3) 

### ISSUE THREAD

**Issue by Innocent259** [microhass/todo-list#7]
Hello @hassanShakur 

![approve](https://github.com/microhass/todo-list/assets/108480851/5f9c711e-951d-4ee2-98ef-644ba7e34d54)

Your project is complete nothing to add because it went beyond expectations :smile: :smile: 

 Highlights :+1: 
1. Your code is clean and followed best practice
2. No linter errors
3. Your design is user-friendly

**Comment by hassanShakur** [comment]
Thanks all for the review. The support is appreciated a lot.
